### ISSUE TITLE
Bitbucket Server error integration

### ISSUE THREAD

**Issue by Marian0** [FinndropStudios/BitRocket#17]
Hello guys! 

I'm trying to integrate this into a Rocket Chat instance but I got the following error in Rocket chat logs:

``` 
rocketchat_logger rocketchat_logger.js:278 [31mIntegrations ➔ Incoming WebHook.error   script.js:1   function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function")}}var config={bitBucketUrl:"https://bitbucket.org/XXXX/YYYYYY",color:"#225159",update:true};var bitBucketUpdate=function(request,i){var text="New "+request.content.refChanges[i].type.toLowerCase()+" on project "+request.content.repository.project.name;var username=request.content.changesets.values[i].toCommit.author.name;var usermail=request.content.changesets.values[i].toCommit.author.emailAddress;var attachment={author_name:username+" ("+usermail+")",title:"Repository \""+request.content.repository.name+"\" in project \""+request.content.repository.project.name+"\" updated",title_link:config["bitBucketUrl"].replace(/\/$/,"")+"/projects/"+request.content.repository.project.key+"/repos/"+request.content.repository.slug+"/browse/",text:username+" updated "+request.content.changesets.values[i].changes.size+(request.content.changeset      TypeError: Cannot read property 'forEach' of undefined       at Script.process_incoming_request (script.js:1:1531)       at evalmachine.<anonymous>:1:8       at ContextifyScript.Script.runInContext (vm.js:59:29)       at ContextifyScript.Script.runInNewContext (vm.js:65:15)       at Object.runInNewContext (vm.js:135:38)       at Object.executeIntegrationRest [as action] (meteor://💻app/packages/rocketchat_integrations.js:2384:22)       at Route.share.Route.Route._callEndpoint (meteor://💻app/packages/nimble_restivus.js:358:32)       at meteor://💻app/packages/nimble_restivus.js:247:33       at packages/simple_json-routes.js:98:9 

```

At Bitbucket webhook status is success. I think there is a bug on the __bitbucket_5_6_native-webhook.js__ script.

Have you any idea about that?

Thank you

**Comment by gelinger777** [comment]
@Marian0  did you fixed this? I have the same issue. It says success but no luck.

**Comment by Marian0** [comment]
@gelinger777 I didn't and now I'm not using it anymore. I hope somebody could help you.
